function [png] = east_stand_pdf()

% Module for East Stand
png.PN_name = 'EastStand';

% pQ*Sec - Queue for security
% p*Stairs - Stairs up to the stand
png.set_of_Ps = {'pQASec', 'pQBSec', 'pQCSec', 'pQDSec', 'pQVIPSec'...
    'pAStairs', 'pBStairs', 'pCStairs', 'pDStairs', 'pVIPStairs'};

% t*Ch(oose)* - Choose the right security
% t*Stairs* - Go up the stairs to the right section
png.set_of_Ts = {'tAChooseA', 'tBChooseB', 'tCChooseB', 'tCChooseC',...
    'tDChooseC','tDChooseD', 'tVIPChVIP', ...
    'tAStairs', 'tBStairs', 'tCStairs1', 'tCStairs2', 'tDStairs1', ...
    'tDStairs2', 'tVIPStairs'};

png.set_of_As = {
    ...% Choose the right security queue
    'tAChooseA', 'pQASec', 1, 'tBChooseB', 'pQBSec', 1, ...
    'tCChooseB', 'pQBSec', 1, 'tCChooseC', 'pQCSec', 1, ...
    'tDChooseC', 'pQCSec', 1, 'tDChooseD', 'pQDSec', 1, ...
    'tVIPChVIP', 'pQVIPSec', 1, ...
    ...% From queue to security module
    'pQASec', 'tASecI', 1, 'pQBSec', 'tBSecI', 1, 'pQCSec', 'tCSecI', 1, ...
    'pQDSec', 'tDSecI', 1, 'pQVIPSec', 'tVIPSecI', 1, ...
    ...% From security module to stairs
    'tASecO', 'pAStairs', 1, 'tBSecO', 'pBStairs', 1, ...
    'tCSecO', 'pCStairs', 1, 'tDSecO', 'pDStairs', 1, ...
    'tVIPSecO', 'pVIPStairs', 1, ...
    'pAStairs', 'tAStairs', 1, 'pBStairs', 'tBStairs', 1, ...
    'pBStairs', 'tCStairs1', 1, 'pCStairs', 'tCStairs2', 1, ...
    'pCStairs', 'tDStairs1' 1, 'pDStairs', 'tDStairs2', 1, ...
    'pVIPStairs', 'tVIPStairs', 1};

png.set_of_Ports = {'tAChooseA', 'tBChooseB', 'tCChooseB', 'tCChooseC',...
    'tDChooseC','tDChooseD', 'tVIPChVIP', ...
    'tAStairs', 'tBStairs', 'tCStairs1', 'tCStairs2', 'tDStairs1', ...
    'tDStairs2', 'tVIPStairs'};