function [png] = h_corr_pdf()

% Module for H corridor (Between sections I and H)
% Only used by ticket holders in section H.
% Used to simulate time taken to move between sections.
png.PN_name = 'HCorridor';

png.set_of_Ps = {'pHIHold', 'pHOHold'};

% tHCorrI, tHCorrO - Input and output for H corridor
% tH* - transition through corridor, amount based on capacity
png.set_of_Ts = {'tHCorrI', 'tHCorrO', ...
    'tH1', 'tH2', 'tH3', 'tH4', 'tH5', ...
    'tH6', 'tH7', 'tH8', 'tH9', 'tH10'};


png.set_of_As = {'tHCorrI', 'pHIHold', 1, 'pHOHold', 'tHCorrO', 1, ...
    'pHIHold', 'tH1', 1, 'pHIHold', 'tH2', 1, ...
    'pHIHold', 'tH3', 1, 'pHIHold', 'tH4', 1, ...
    'pHIHold', 'tH5', 1, 'pHIHold', 'tH6', 1, ...
    'pHIHold', 'tH7', 1, 'pHIHold', 'tH8', 1, ...
    'pHIHold', 'tH9', 1, 'pHIHold', 'tH10', 1, ...
    'tH1', 'pHOHold', 1, 'tH2', 'pHOHold', 1, ...
    'tH3', 'pHOHold', 1, 'tH4', 'pHOHold', 1, ...
    'tH5', 'pHOHold', 1, 'tH6', 'pHOHold', 1, ...
    'tH7', 'pHOHold', 1, 'tH8', 'pHOHold', 1, ...
    'tH9', 'pHOHold', 1, 'tH10', 'pHOHold', 1};

png.set_of_Ports = {'tHCorrI', 'tHCorrO'};