function [png] = hi_corr_pdf()

% Module for HI corridor (Between sections J and I)
% Only used by ticket holders in sections H and I
% Used to simulate time taken to move between sections
png.PN_name = 'HICorridor';

png.set_of_Ps = {'pHIIHold', 'pHIOHold'};

% tHICorrI, tHICorrO - Input and output for HI corridor
% tHI* - transition through corridor, amount based on capacity
png.set_of_Ts = {'tHICorrI', 'tHICorrO', ...
    'tHI1', 'tHI2', 'tHI3', 'tHI4', 'tHI5', ...
    'tHI6', 'tHI7', 'tHI8', 'tHI9', 'tHI10'};

png.set_of_As = {'tHICorrI', 'pHIIHold', 1, 'pHIOHold', 'tHICorrO', 1, ...
    'pHIIHold', 'tHI1', 1, 'pHIIHold', 'tHI2', 1, ...
    'pHIIHold', 'tHI3', 1, 'pHIIHold', 'tHI4', 1, ...
    'pHIIHold', 'tHI5', 1, 'pHIIHold', 'tHI6', 1, ...
    'pHIIHold', 'tHI7', 1, 'pHIIHold', 'tHI8', 1, ...
    'pHIIHold', 'tHI9', 1, 'pHIIHold', 'tHI10', 1, ...
    'tHI1', 'pHIOHold', 1, 'tHI2', 'pHIOHold', 1, ...
    'tHI3', 'pHIOHold', 1, 'tHI4', 'pHIOHold', 1, ...
    'tHI5', 'pHIOHold', 1, 'tHI6', 'pHIOHold', 1, ...
    'tHI7', 'pHIOHold', 1, 'tHI8', 'pHIOHold', 1, ...
    'tHI9', 'pHIOHold', 1, 'tHI10', 'pHIOHold', 1};

png.set_of_Ports = {'tHICorrI', 'tHICorrO'};