function [png] = hijk_corr_pdf()

% Module for HIJK corridor (Between sections L and K)
% Only used by ticket holders in sections H, I, J and K
% Used to simulate time taken to move between sections
png.PN_name = 'HIJKCorridor';

png.set_of_Ps = {'pHIJKIHold', 'pHIJKOHold'};

% tHIJKCorrI, tHIJKCorrO - Input and output for HIJK corridor
% tHIJK* - transition through corridor, amount based on capacity
png.set_of_Ts = {'tHIJKCorrI', 'tHIJKCorrO', ...
    'tHIJK1', 'tHIJK2', 'tHIJK3', 'tHIJK4', 'tHIJK5', ...
    'tHIJK6', 'tHIJK7', 'tHIJK8', 'tHIJK9', 'tHIJK10'};

png.set_of_As = {'tHIJKCorrI', 'pHIJKIHold', 1, 'pHIJKOHold', 'tHIJKCorrO', 1, ...
    'pHIJKIHold', 'tHIJK1', 1, 'pHIJKIHold', 'tHIJK2', 1, ...
    'pHIJKIHold', 'tHIJK3', 1, 'pHIJKIHold', 'tHIJK4', 1, ...
    'pHIJKIHold', 'tHIJK5', 1, 'pHIJKIHold', 'tHIJK6', 1, ...
    'pHIJKIHold', 'tHIJK7', 1, 'pHIJKIHold', 'tHIJK8', 1, ...
    'pHIJKIHold', 'tHIJK9', 1, 'pHIJKIHold', 'tHIJK10', 1, ...
    'tHIJK1', 'pHIJKOHold', 1, 'tHIJK2', 'pHIJKOHold', 1, ...
    'tHIJK3', 'pHIJKOHold', 1, 'tHIJK4', 'pHIJKOHold', 1, ...
    'tHIJK5', 'pHIJKOHold', 1, 'tHIJK6', 'pHIJKOHold', 1, ...
    'tHIJK7', 'pHIJKOHold', 1, 'tHIJK8', 'pHIJKOHold', 1, ...
    'tHIJK9', 'pHIJKOHold', 1, 'tHIJK10', 'pHIJKOHold', 1};

png.set_of_Ports = {'tHIJKCorrI', 'tHIJKCorrO'};