function [png] = north_security_pdf()

% Module for North security
png.PN_name = 'NorthSecurity';

% pNSecGQ - Queue for security check
% pNIHold, pNOHold - Hold for security check
png.set_of_Ps = {'pNIHold', 'pNOHold', 'pNSecGQ'};

% tNSecI, tNSecO - Input and output for security check
% tNTs* - Turnstiles
% tNSecG* - Security guards
png.set_of_Ts = {'tNSecI', 'tNSecO', ...
    'tNTs1', 'tNTs2', 'tNTs3', 'tNTs4', 'tNTs5', 'tNTs6', 'tNTs7', ...
    'tNSecG1', 'tNSecG2', 'tNSecG3', 'tNSecG4', 'tNSecG5', ...
    'tNSecG6', 'tNSecG7', 'tNSecG8', 'tNSecG9', 'tNSecG10'};

png.set_of_As = {'tNSecI', 'pNIHold', 1, 'pNOHold', 'tNSecO', 1, ...
    ...% Turnstiles
    'pNIHold', 'tNTs1', 1, 'pNIHold', 'tNTs2', 1, 'pNIHold', 'tNTs3', 1, ...
    'pNIHold', 'tNTs4', 1, 'pNIHold', 'tNTs5', 1, 'pNIHold', 'tNTs6', 1, ...
    'pNIHold', 'tNTs7', 1, ...
    'tNTs1', 'pNSecGQ', 1, 'tNTs2', 'pNSecGQ', 1, 'tNTs3', 'pNSecGQ', 1, ...
    'tNTs4', 'pNSecGQ', 1, 'tNTs5', 'pNSecGQ', 1, 'tNTs6', 'pNSecGQ', 1, ...
    'tNTs7', 'pNSecGQ', 1, ...
    ...% Security guards
    'pNSecGQ', 'tNSecG1', 1, 'pNSecGQ', 'tNSecG2', 1, ...
    'pNSecGQ', 'tNSecG3', 1, 'pNSecGQ', 'tNSecG4', 1, ...
    'pNSecGQ', 'tNSecG5', 1, 'pNSecGQ', 'tNSecG6', 1, ...
    'pNSecGQ', 'tNSecG7', 1, 'pNSecGQ', 'tNSecG8', 1, ...
    'pNSecGQ', 'tNSecG9', 1, 'pNSecGQ', 'tNSecG10', 1, ...
    'tNSecG1', 'pNOHold', 1, 'tNSecG2', 'pNOHold', 1, ...
    'tNSecG3', 'pNOHold', 1, 'tNSecG4', 'pNOHold', 1, ...
    'tNSecG5', 'pNOHold', 1, 'tNSecG6', 'pNOHold', 1, ...
    'tNSecG7', 'pNOHold', 1, 'tNSecG8', 'pNOHold', 1, ...
    'tNSecG9', 'pNOHold', 1, 'tNSecG10', 'pNOHold', 1};

% Avoid queue in holding places
png.set_of_Is = {'pNIHold', 'tNSecI', 7};

png.set_of_Ports = {'tNSecI', 'tNSecO'};