clear;

global global_info,
global_info.MAX_LOOP = 100;
global_info.DELTA_TIME = 1;

% Sold tickets
global_info.H_COUNT = 950; % Max 950 - Avg 285
global_info.I_COUNT = 795; % Max 795 - Avg 397
global_info.J_COUNT = 737; % Max 737 - Avg 515
global_info.K_COUNT = 732; % Max 732 - Avg 732
global_info.L_COUNT = 795; % Max 795 - Avg 795

% Arrival times
arrive_mean = 16 * 60 * 60 + 15 * 60;
arrive_sd = 20 * 60;
global_info.H_ARRIVE_TIME = sort(normrnd(arrive_mean, arrive_sd, [1, global_info.H_COUNT]), 'descend');
global_info.I_ARRIVE_TIME = sort(normrnd(arrive_mean, arrive_sd, [1, global_info.I_COUNT]), 'descend');
global_info.J_ARRIVE_TIME = sort(normrnd(arrive_mean, arrive_sd, [1, global_info.J_COUNT]), 'descend');
global_info.K_ARRIVE_TIME = sort(normrnd(arrive_mean, arrive_sd, [1, global_info.K_COUNT]), 'descend');
global_info.L_ARRIVE_TIME = sort(normrnd(arrive_mean, arrive_sd, [1, global_info.L_COUNT]), 'descend');

% Simulation start and stop time
% Normal match start time is 17:00
global_info.START_AT = [15 30 00];
global_info.STOP_AT = [17 30 00];

pns = pnstruct({'west_entrance_imc_pdf', 'north_security_pdf', ...
                    'west_corridor_imc_pdf', 'h_corr_pdf', 'hi_corr_pdf', ...
                    'hij_corr_pdf', 'hijk_corr_pdf', 'west_stand_pdf'});

dyn.m0 = {'pHStart', global_info.H_COUNT, ...
          'pIStart', global_info.I_COUNT, ...
          'pJStart', global_info.J_COUNT, ...
          'pKStart', global_info.K_COUNT, ...
          'pLStart', global_info.L_COUNT, ...
      };

CORR_FT = 5; % Corridor firing time - time taken to walk between sections
TS_FT = 5; % Turnstile firing time
G_FT = 10; % Security guard firing time

% tNTs* - Security turnstiles
% tNSecG* - Security guards
% t**** - Corridors between sections
dyn.ft = {'tNTs1', TS_FT, 'tNTs2', TS_FT, 'tNTs3', TS_FT, 'tNTs4', TS_FT, ...
              'tNTs5', TS_FT, 'tNTs6', TS_FT, 'tNTs7', TS_FT, ...
              'tNSecG1', G_FT, 'tNSecG2', G_FT, 'tNSecG3', G_FT, 'tNSecG4', G_FT, ...
              'tNSecG5', G_FT, 'tNSecG6', G_FT, 'tNSecG7', G_FT, 'tNSecG8', G_FT, ...
              'tNSecG9', G_FT, 'tNSecG10', G_FT, ...
              'tHIJK1', CORR_FT, 'tHIJK2', CORR_FT, 'tHIJK3', CORR_FT, 'tHIJK4', CORR_FT, ...
              'tHIJK5', CORR_FT, 'tHIJK6', CORR_FT, 'tHIJK7', CORR_FT, 'tHIJK8', CORR_FT, ...
              'tHIJK9', CORR_FT, 'tHIJK10', CORR_FT, ...
              'tHIJ1', CORR_FT, 'tHIJ2', CORR_FT, 'tHIJ3', CORR_FT, 'tHIJ4', CORR_FT, ...
              'tHIJ5', CORR_FT, 'tHIJ6', CORR_FT, 'tHIJ7', CORR_FT, 'tHIJ8', CORR_FT, ...
              'tHIJ9', CORR_FT, 'tHIJ10', CORR_FT, ...
              'tHI1', CORR_FT, 'tHI2', CORR_FT, 'tHI3', CORR_FT, 'tHI4', CORR_FT, ...
              'tHI5', CORR_FT, 'tHI6', CORR_FT, 'tHI7', CORR_FT, 'tHI8', CORR_FT, ...
              'tHI9', CORR_FT, 'tHI10', CORR_FT, ...
              'tH1', CORR_FT, 'tH2', CORR_FT, 'tH3', CORR_FT, 'tH4', CORR_FT, ...
              'tH5', CORR_FT, 'tH6', CORR_FT, 'tH7', CORR_FT, 'tH8', CORR_FT, ...
              'tH9', CORR_FT, 'tH10', CORR_FT, ...
              'allothers', 0.00001};

pni = initialdynamics(pns, dyn);

Sim_Results = gpensim(pni);


figure('Name', 'West Stand Seats'), plotp(Sim_Results, {'pLSeats', 'pKSeats', 'pJSeats', 'pISeats', 'pHSeats'});
figure('Name', 'West Stand North Queue'), plotp(Sim_Results, {'pNQ'});
figure('Name', 'West Stand Security Guard Queue'), plotp(Sim_Results, {'pNSecGQ'});
figure('Name', 'West Stand Corridors'), plotp(Sim_Results, {'pHIJKIHold', 'pHIJIHold', 'pHIIHold', 'pHIHold'});
figure('Name', 'West Stand Not Arrived'), plotp(Sim_Results, {'pHStart', 'pIStart', 'pJStart', 'pKStart', 'pLStart'});
%prnss(Sim_Results);
