function [png] = west_corridor_imc_pdf()

% Module for West Corridor IMC
png.PN_name = 'WestCorridorIMC';

% pNCorr - Holding place after security check
% pLToK, pKToJ, pJToI, pIToH - Holding places for each section
png.set_of_Ps = {'pNCorr', 'pLToK', 'pKToJ', 'pJToI', 'pIToH'};

png.set_of_Ts = {};

png.set_of_As = {'tNSecO', 'pNCorr', 1, ...
    'pNCorr', 'tHIJKCorrI' 1, 'tHIJKCorrO', 'pLToK', 1, ...
    'pLToK', 'tHIJCorrI' 1, 'tHIJCorrO', 'pKToJ', 1, ...
    'pKToJ', 'tHICorrI' 1, 'tHICorrO', 'pJToI', 1, ...
    'pJToI', 'tHCorrI' 1, 'tHCorrO', 'pIToH', 1, ...
    'pNCorr', 'tLStairs', 1, 'pLToK', 'tKStairs', 1, ...
    'pKToJ', 'tJStairs', 1, 'pJToI', 'tIStairs', 1, ...
    'pIToH', 'tHStairs', 1};
